"""initial_tables

Revision ID: 011a25b758be
Revises: 
Create Date: 2026-08-19 09:28:51.017137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '011a25b758be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sports_id'), 'sports', ['id'], unique=False)
    op.create_index(op.f('ix_sports_name'), 'sports', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PLAYER', 'COACH', 'SCOUT', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('sport', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('achievements', sa.Text(), nullable=True),
    sa.Column('profile_image', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_sport'), 'players', ['sport'], unique=False)
    op.create_index(op.f('ix_players_user_id'), 'players', ['user_id'], unique=True)
    op.create_table('performance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('stamina', sa.Float(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('agility', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('matches_played', sa.Integer(), nullable=False),
    sa.Column('assessment_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_records_assessment_date'), 'performance_records', ['assessment_date'], unique=False)
    op.create_index(op.f('ix_performance_records_id'), 'performance_records', ['id'], unique=False)
    op.create_index(op.f('ix_performance_records_player_id'), 'performance_records', ['player_id'], unique=False)
    op.create_table('shortlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'player_id', name='uq_user_player_shortlist')
    )
    op.create_index(op.f('ix_shortlists_id'), 'shortlists', ['id'], unique=False)
    op.create_index(op.f('ix_shortlists_player_id'), 'shortlists', ['player_id'], unique=False)
    op.create_index(op.f('ix_shortlists_user_id'), 'shortlists', ['user_id'], unique=False)
    op.create_table('training_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('focus_areas', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_recommendations_coach_id'), 'training_recommendations', ['coach_id'], unique=False)
    op.create_index(op.f('ix_training_recommendations_id'), 'training_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_training_recommendations_player_id'), 'training_recommendations', ['player_id'], unique=False)
    op.create_table('ai_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('performance_id', sa.Integer(), nullable=False),
    sa.Column('performance_score', sa.Float(), nullable=False),
    sa.Column('talent_score', sa.Float(), nullable=False),
    sa.Column('potential_level', sa.String(length=50), nullable=False),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['performance_id'], ['performance_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analysis_id'), 'ai_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_ai_analysis_performance_id'), 'ai_analysis', ['performance_id'], unique=False)
    op.create_index(op.f('ix_ai_analysis_player_id'), 'ai_analysis', ['player_id'], unique=False)
    op.create_index(op.f('ix_ai_analysis_potential_level'), 'ai_analysis', ['potential_level'], unique=False)
    op.create_index(op.f('ix_ai_analysis_talent_score'), 'ai_analysis', ['talent_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_analysis_talent_score'), table_name='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_potential_level'), table_name='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_player_id'), table_name='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_performance_id'), table_name='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_id'), table_name='ai_analysis')
    op.drop_table('ai_analysis')
    op.drop_index(op.f('ix_training_recommendations_player_id'), table_name='training_recommendations')
    op.drop_index(op.f('ix_training_recommendations_id'), table_name='training_recommendations')
    op.drop_index(op.f('ix_training_recommendations_coach_id'), table_name='training_recommendations')
    op.drop_table('training_recommendations')
    op.drop_index(op.f('ix_shortlists_user_id'), table_name='shortlists')
    op.drop_index(op.f('ix_shortlists_player_id'), table_name='shortlists')
    op.drop_index(op.f('ix_shortlists_id'), table_name='shortlists')
    op.drop_table('shortlists')
    op.drop_index(op.f('ix_performance_records_player_id'), table_name='performance_records')
    op.drop_index(op.f('ix_performance_records_id'), table_name='performance_records')
    op.drop_index(op.f('ix_performance_records_assessment_date'), table_name='performance_records')
    op.drop_table('performance_records')
    op.drop_index(op.f('ix_players_user_id'), table_name='players')
    op.drop_index(op.f('ix_players_sport'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sports_name'), table_name='sports')
    op.drop_index(op.f('ix_sports_id'), table_name='sports')
    op.drop_table('sports')
    # ### end Alembic commands ###
